In [187]:
import numpy as np
from collections import Counter

In [188]:
class KNN:
    def __init__(self,k):
        self.k = k
        self.x_train=None
        self.y_train = None
    def fit(self,X,Y):
        self.x_train=X
        self.y_train=Y
    def predict_one(self,x):
        distances = [np.sqrt(np.sum((x-x_tr)**2)) for x_tr in self.x_train]
        k_indices = np.argsort(np.array(distances))[:self.k]
        return Counter(self.y_train[k_indices]).most_common(1)[0][0]
    def predict(self,X):
        return np.array([self.predict_one(x) for x in X])



In [197]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,r2_score


In [190]:
data = load_iris()
X = data.data
Y = data.target

In [191]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=41)

In [192]:
model = KNN(5)

In [193]:
model.fit(x_train,y_train)

In [194]:
pred = model.predict(x_test)

In [195]:
pred

array([2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 0, 2, 0, 2, 0, 0, 1, 2,
       0, 0, 1, 1, 1, 1, 0, 1])

In [198]:
print(confusion_matrix(y_test,pred))
print("accuracy:",accuracy_score(y_test,pred))
print("r2 score:",r2_score(y_test,pred))


[[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]
accuracy: 0.9666666666666667
r2 score: 0.9472759226713533
