In [1]:
import numpy as np

In [2]:
class softmax:
    def __init__(self,epochs,classes,random_st,lr):
        self.epochs = epochs
        self.random_st = random_st
        self.classes = classes
        self.lr = lr
        self.weights = None
        self.bias = None
    def get_score(self,X):
        return np.dot(X,self.weights)+self.bias
    def get_prob(self,scores):
        scores = scores-np.max(scores,axis=1,keepdims=True)
        return np.exp(scores)/np.sum(np.exp(scores),axis=1,keepdims=True)
    def to_one_hot(self,Y):
        return np.eye(self.classes)[Y]
    def compute_gradients(self,prob,one_hot,X,m_samp):
        d_score = prob-one_hot
        dw = (1/m_samp)*np.dot(X.T,d_score)
        db =(1/m_samp)*np.sum(d_score)
        self.weights = self.weights-self.lr*dw
        self.bias = self.bias-self.lr*db    
    def fit(self,X,Y):
        n_samp,m_feat = X.shape
        self.weights = np.zeros((m_feat,self.classes))
        self.bias=np.zeros((1,self.classes))
        one_hot = self.to_one_hot(Y.astype(int))
        for i in range(self.epochs):
            scores = self.get_score(X)
            prob = self.get_prob(scores)
            
            self.compute_gradients(prob,one_hot,X,n_samp)
    def predict(self,X):
        scores = np.dot(X,self.weights)+self.bias
        prob = np.exp(scores)/np.sum(np.exp(scores))
        return np.argmax(prob,axis=1)

            


    
        


In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [4]:
data = load_iris()


In [5]:
X = data.data
Y = data.target



In [6]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=41)

In [7]:
model = softmax(1000,3,41,0.01)

In [8]:
model.fit(x_train,y_train)

In [9]:
pred = model.predict(x_test)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,r2_score,precision_score

In [13]:
print(confusion_matrix(y_test,pred))
print('accuracy_score:',accuracy_score(y_test,pred))

print("r2 score:",r2_score(y_test,pred))


[[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]
accuracy_score: 0.9666666666666667
r2 score: 0.9472759226713533
